### ISSUE TITLE
Prompt css style and customization?

### ISSUE THREAD

**Issue by lifan0127** [windingwind/zotero-plugin-toolkit#20]
This is really nice library. I noticed a display issue related to the prompt window under Ubuntu dark mode:

![image](https://user-images.githubusercontent.com/7218193/227321344-40e38ea8-b428-43b1-8393-ff29c00a793b.png)

I believe it is related to the border-radius setting for the input: https://github.com/windingwind/zotero-plugin-toolkit/blob/e896eaa1a9f6d1ba80be7bbf3cae6b5ef2548651/src/managers/prompt.ts#L638

More broadly, how can I customize this prompt UI element, such as its style and keyboard shortcut?

Thanks!

**Comment by windingwind** [comment]
Hi, thanks for the feedback. I will look into this bug later.

The Prompt is shared by all plugins, thus changing its style will also affect other plugins. Adding CSS to the main window can change the looking of the Prompt.

**Comment by lifan0127** [comment]
"The Prompt is shared by all plugins" - so if multiple plug-ins use the prompt feature, what happens when user press shift+p?

**Comment by windingwind** [comment]
The `register` and `unregister` of all Manager modules work under a global scope. One and only one prompt will be initialized on the first call of `register` from any plugin, and since then any `register` from any plugin will add a new command to the prompt.

Multiple plugins share the same Prompt and their commands can all be called or searched. This is actually happening in Zotero already.

**Comment by lifan0127** [comment]
Thanks for your reply! I understand how the prompt works now.
