### ISSUE TITLE
Cannot find namespace '_ZoteroTypes'.

### ISSUE THREAD

**Issue by retorquere** [windingwind/zotero-plugin-toolkit#73]
When I import the zotero toolkit, I'm getting errors on missing namespaces like

```
node_modules/zotero-plugin-toolkit/dist/basic.d.ts:25:40 - error TS2503: Cannot find namespace '_ZoteroTypes'.

25     getGlobal(k: "Zotero" | "zotero"): _ZoteroTypes.Zotero;
                                          ~~~~~~~~~~~~
```

my tsconfig is

```
{
  "compilerOptions": {
    "declaration": false,
    "allowUnreachableCode": false,
    "importHelpers": true,
    "target": "es2017",
    "disableSizeLimit": true,
    "module": "commonjs",
    "noImplicitAny": false,
    "removeComments": false,
    "preserveConstEnums": false,
    "sourceMap": false,
    "downlevelIteration": true,
    "lib": [ "es2019", "dom", "ES2021.WeakRef" ],
    "types": [ "node" ],
    "typeRoots": [ "./node_modules/@types" ]
  },
  "include": [ "bootstrap.ts", "content/folder-import.ts", "content/globals.d.ts", "node_modules/zotero-types" ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}

```

**Comment by northword** [comment]
```diff
{
  "compilerOptions": {
    "declaration": false,
    "allowUnreachableCode": false,
    "importHelpers": true,
    "target": "es2017",
    "disableSizeLimit": true,
    "module": "commonjs",
    "noImplicitAny": false,
    "removeComments": false,
    "preserveConstEnums": false,
    "sourceMap": false,
    "downlevelIteration": true,
    "lib": [ "es2019", "dom", "ES2021.WeakRef" ],
--- "types": [ "node" ],
--- "typeRoots": [ "./node_modules/@types" ]
+++ "skipLibCheck": true
  },
  "include": [ "bootstrap.ts", "content/folder-import.ts", "content/globals.d.ts", "node_modules/zotero-types" ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
```

**Comment by retorquere** [comment]
Is there a way without skiplibcheck? I have some libraries that offer typings, I'd prefer to keep those. Right now I just remove all d.ts files from the plugin toolkit.

**Comment by windingwind** [comment]
The gecko types used by the package `zotero-types` conflict heavily with the built-in TS types, such as `Window`, `Document`, and all kinds of DOM things. This package relies on these types.

I'm not sure if there is a way to let the TS server recognize these TS definitions without skipping the lib check... I tried some suggestions from LLM but had no luck.

**Comment by retorquere** [comment]
I don't follow. The problem exists because this package pulls in zotero-types? Geen why not remove that dependency?

**Comment by windingwind** [comment]
Actually I didn't see this error if I set `skipLibCheck` to false, probably because I have `node_modules/zotero-types` included in the project's tsconfig. But other ts errors are mostly from the cause I mentioned above:

```
Found 1404 errors in 8 files.

Errors  Files
   121  node_modules/@types/react/index.d.ts:4312
    81  node_modules/typescript/lib/lib.dom.d.ts:23
     1  node_modules/zotero-types/types/gecko/index.d.ts:24
  1184  node_modules/zotero-types/types/gecko/lib.gecko.dom.d.ts:9
    13  node_modules/zotero-types/types/gecko/lib.gecko.tweaks.d.ts:25
     1  ../zotero-plugin-toolkit/dist/helpers/virtualizedTable.d.ts:1
     1  ../zotero-plugin-toolkit/dist/tools/ui.d.ts:335
     2  ../zotero-plugin-toolkit/node_modules/@types/react/index.d.ts:4318
```

> Geen why not remove that dependency?

Well, the `zotero-types` provides TS definitions for both Zotero and Gecko platform (fetched from Mozilla's) and it's helpful for development in Zotero's environment... Unless you want to duplicate all that again manually, otherwise I don't see any reason to remove it.

**Comment by windingwind** [comment]
Just updated all dependencies and now conflict should only exists between `node_modules/typescript/lib/lib.dom.d.ts` and `node_moduels/zotero-types/gecko/lib.gecko.dom.d.ts`

**Comment by windingwind** [comment]
Just checked the https://github.com/retorquere/zotero-folder-import, it's because the `zotero-types` is not visible to the TS compiler. If you add `"node_modules/zotero-types"` to `include` and remove `"node_modules"` from `exclude`, it should be recognized; but still, the gecko types conflict with the TS builtin ones.

**Comment by retorquere** [comment]
I've updated but I still get lots of errors around `Cannot find namespace '_ZoteroTypes'` and `Cannot find name 'XUL...Element'`.

> Unless you want to duplicate all that again manually, otherwise I don't see any reason to remove it.

I'd prefer not to duplicate anything manually, but adding `zotero-types` still leaves me with the `_ZoteroTypes` and `XUL...Element` errors.

I currently just run

```
find node_modules/zotero-plugin-toolkit -name \*.d.ts -exec rm {} \;
```

before my build and then I can proceed.

> The gecko types used by the package zotero-types conflict heavily with the built-in TS types, such as Window, Document, and all kinds of DOM things. This package relies on these types. I don't know if we can allow lib-checking on these dependencies.

Maybe I just don't understand what this says. It sounds like your lib depends heavily on zotero-types? But how does that cause these `_ZoteroTypes` errors?

But if there's nothing that can be done about this then that's just how it is. Setting `skipLibCheck` seems like the nuclear option to solving this problem though.

**Comment by retorquere** [comment]
> Just checked the https://github.com/retorquere/zotero-folder-import, it's because the `zotero-types` is not visible to the TS compiler. If you add `"node_modules/zotero-types"` to `include` and remove `"node_modules"` from `exclude`, it should be recognized; but still, the gecko types conflict with the TS builtin ones.

Ah, so I had effectively set skipLibCheck? Weird, I thought I was getting typings from `zotero-plugin`. But you're right, the `_ZoteroTypes` errors are gone but replaced by countless other errors that are likely from the clash with the gecko types.

**Comment by retorquere** [comment]
My build runs when I remove `node_modules` from `exclude` (and remove all d.ts files from plugin-toolkit). If that's the best that can be achieved then so be it.

**Comment by windingwind** [comment]
We can try to somehow... fix these gecko errors, maybe manually fix them all and generate a patch file so that hopefully the next time gecko updates something we don't need to do it again. (And presumably we don't need to update gecko types frequently)

Another option would be to include a copy of `lib.dom.d.ts` along with gecko's `dom.d.ts` , with `@ts-nocheck`, and ban the default DOM lib from the tsconfig.

I don't know if there are better options... What do you think?

**Comment by retorquere** [comment]
I've been battling the same problems, I've used forced-typecasting in a lot of places. Another problem I've had is that I want to have `Zotero.<plugin name>` to be typed, and for that I need to re-type the Zotero object.

**Comment by windingwind** [comment]
> I've been battling the same problems, I've used forced-typecasting in a lot of places.

If we replace the default `dom.d.ts`, it should be fine without modifying anything. All/most of the errors from gecko are duplicate declaration, and the TS server can tolerate this.

> Another problem I've had is that I want to have Zotero.<plugin name> to be typed, and for that I need to re-type the Zotero object.

Currently the `Zotero` is defined as a const variable in `zotero-types`, but it's possible to make it a `module` and then you can extend it elsewhere. Currently I am injecting a reference to this plugin instance to the globalThis of the plugin sandbox so that plugin code can access it with types.

**Comment by retorquere** [comment]
> TS server

what is a TS Server?

> Currently the Zotero is defined as a const variable in zotero-types, but it's possible to make it a module and then you can extend it elsewhere. Currently I am injecting a reference to this plugin instance to the globalThis of the plugin sandbox so that plugin code can access it with types.

That seems desirable

**Comment by windingwind** [comment]
> what is a TS Server?

I meant to say the typescript language server that analyzes and compiles TS code

**Comment by retorquere** [comment]
Is this something related to language servers/visual-studio type editors? I'm a command line guy, I invoke `tsc` to compile and use `vi` for editing.

**Comment by windingwind** [comment]
They should work the same way -  but maybe that's how it's called in IDEs like vscode, idk. Anyway, I'll make some observations in that direction.
